apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: helloworld
  labels:
    app: mysql
data:
  master.cnf: |
    [mysqld]
  slave.cnf: |
    [mysqld]
    super-read-only
  my.cnf: |
    [mysqld]
    log-bin
    binlog_format = row
    gtid-mode = on
    enforce-gtid-consistency = on
    log-slave-updates
    !includedir /etc/mysql/conf.d/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: initdb
  namespace: helloworld
  labels:
    app: initdb
data:
  initdb.sql: |-
    CREATE USER IF NOT EXISTS 'backuper'@'%' IDENTIFIED BY 'mysql_pass';
    CREATE USER IF NOT EXISTS 'readiness'@'%' IDENTIFIED BY 'readiness';