apiVersion: v1
kind: Service
metadata:
  namespace: data
  name: mysql-service
spec:
  ports:
  - name: mysql-service
    port: 3306
    protocol: TCP
  clusterIP: None
  selector:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  namespace: data
  name: mysql-read-service
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
  selector:
    app: mysql