apiVersion: v1
kind: Service
metadata:
  namespace: helloworld
  name: mysql-master
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-master
---
apiVersion: v1
kind: Service
metadata:
  namespace: helloworld
  name: mysql-slave
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-slave