server:
  servlet:
    context-path: /api/v1
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DATABASE_NAME}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  redis:
    cluster:
      nodes: redis-service.redis-cluster.svc.cluster.local:6379
      timeout: 2000
      max-redirects: 7
logging:
  config: classpath:logback-spring.xml