apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MWYyZDFlMmU2N2Rm
  MYSQL_REPLICATION_USER: YWRtaW4=
  MYSQL_REPLICATION_PASSWORD: MWYyZDFlMmU2N2Rm
  MYSQL_USER: YWRtaW4=
  MYSQL_PASSWORD: MWYyZDFlMmU2N2Rm