apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-slave
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  capacity:
    storage: 50Mi
  local:
    path: /home/k8s/slave/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - paas-cnp-k8s-kce-01  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-slave
  namespace: helloworld-cluster
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  volumeName: mysql-pv-slave