apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: helloworld
  labels:
    app: helloworld-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-app
  template:
    metadata:
      labels:
        app: helloworld-app
    spec:
      containers:
      - name: helloworld-app
        image: roydeng0428/helloworld-java:1.0.0
        ports:
          - containerPort: 8080
        env:
          - name: MYSQL_DATABASE_NAME
            value: helloworlddb
          - name: MYSQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: mysql-account
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: mysql-password
          - name: RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: rabbitmq-user
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: rabbitmq-password
          - name: MAILGUN_USERNAME
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: mailgun-user
          - name: MAILGUN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: mailgun-password
        imagePullPolicy: Always