apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  namespace: helloworld-cluster
spec:
  rules:
  - host: k8s-test.com
    http:
      paths:
      - path: /test-redis
        backend:
          serviceName: helloworld-app-service
          servicePort: 80