apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: helloworld-ingress
  namespace: helloworld
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: helloworld-service
            port:
              number: 80
        path: /
        pathType: Prefix