apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app
spec:
  selector:
    app: helloworld-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer