apiVersion: v1
kind: Service
metadata:
  name: helloworld-app-service
  namespace: helloworld-cluster
spec:
  selector:
    app: helloworld-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer