apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: helloworld
type: Opaque
data:
  erlang-cookie: MTIzajE5dWVkYXM3ZGFkODEwMjNqMTM5ZGph
  default-user: dXNlcg==
  default-password: cGFzc3dvcmQ=