server:
  servlet:
    context-path: /api/v1
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      master:
        name: master
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DATABASE_NAME}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}
      slave:
        name: slave
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DATABASE_NAME}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}
  redis:
    cluster:
      nodes: redis-service.redis-cluster.svc.cluster.local:6379
      timeout: 2000
      max-redirects: 7
  rabbitmq:
    host: 
    port: 5672
    username: 
    password: 
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100
  mail:
    host: 
    username: 
    password: 
    from: 
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
    port: 465
    protocol: smtp
logging:
  config: classpath:logback-spring.xml
helloworld:
  app:
    jwtSecret: helloWorldSecretKey
    jwtExpirationMs: 86400000