server:
  servlet:
    context-path: /api/v1
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      master:
        name: master
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://mysql-master-0.mysql-service:3306/${MYSQL_DATABASE_NAME}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: ${MYSQL_USERNAME}
        password: ${MYSQL_PASSWORD}
      slave:
        name: slave
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://mysql-slave-0.mysql-service:3306/${MYSQL_DATABASE_NAME}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: ${MYSQL_USERNAME}
        password: ${MYSQL_PASSWORD}
  data:
    redis:
      connect-timeout: 2000
      cluster:
        nodes: redis-service.helloworld.svc.cluster.local:6379
        max-redirects: 7
  rabbitmq:
    addresses: rabbitmq-0.rabbitmq.helloworld.svc.cluster.local:5672,rabbitmq-1.rabbitmq.helloworld.svc.cluster.local:5672,rabbitmq-2.rabbitmq.helloworld.svc.cluster.local:5672
    address-shuffle-mode: inorder
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100
  mail:
    host: smtp.mailgun.org
    port: 587
    username: ${MAILGUN_USERNAME}
    password: ${MAILGUN_PASSWORD}
    properties:
      mail.transport.protocol: smtp
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.auth: true
      mail.smtp.from: test@gmail.com
    default-encoding: UTF-8
    test-connection: false
logging:
  config: classpath:logback-spring.xml
helloworld:
  app:
    jwtSecret: helloWorldSecretKey
    jwtExpirationMs: 86400000